"""Publication-style figure helpers for AgroEcoSim."""

from __future__ import annotations

from html import escape
from pathlib import Path

import numpy as np
import pandas as pd


COLORS = {
    "forest": "#1d3d32",
    "coral": "#d97955",
    "blue": "#277da1",
    "gold": "#e5b84d",
    "violet": "#6f5c85",
    "grid": "#d9e2dc",
    "paper": "#f7f9f5",
    "ink": "#18231f",
    "muted": "#5f6e67",
}


def _polyline(points: list[tuple[float, float]], color: str) -> str:
    coordinates = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    circles = "".join(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5" fill="{color}"/>' for x, y in points)
    return f'<polyline points="{coordinates}" fill="none" stroke="{color}" stroke-width="4"/>{circles}'


def write_scenario_comparison(summary: pd.DataFrame, output_path: str | Path) -> Path:
    """Write a dependency-free SVG comparison of scenario metrics."""

    path = Path(output_path)
    width, height = 1100, 560
    left, right, top, bottom = 90, 1030, 120, 440
    count = len(summary)
    x_positions = np.linspace(left, right, count)

    def y_scale(values: pd.Series, low: float, high: float) -> list[float]:
        return [bottom - (float(value) - low) / (high - low) * (bottom - top) for value in values]

    stability_points = list(zip(x_positions, y_scale(summary["stability_score"], 0.35, 0.85)))
    pressure_points = list(zip(x_positions, y_scale(summary["chemical_pressure"], 0.0, 1.0)))
    labels = "".join(
        f'<text x="{x:.1f}" y="472" text-anchor="middle" font-size="11" fill="{COLORS["muted"]}">{escape(str(label))}</text>'
        for x, label in zip(x_positions, summary["scenario"])
    )
    grid = "".join(
        f'<line x1="{left}" y1="{y}" x2="{right}" y2="{y}" stroke="{COLORS["grid"]}"/>'
        for y in np.linspace(top, bottom, 5)
    )
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}">
<rect width="{width}" height="{height}" fill="{COLORS['paper']}"/>
<text x="60" y="58" font-family="Arial" font-size="26" font-weight="700" fill="{COLORS['ink']}">Scenario comparison</text>
<text x="60" y="84" font-family="Arial" font-size="13" fill="{COLORS['muted']}">Generated by the AgroEcoSim demo pipeline</text>
{grid}
{_polyline(stability_points, COLORS['forest'])}
{_polyline(pressure_points, COLORS['coral'])}
{labels}
<circle cx="780" cy="62" r="5" fill="{COLORS['forest']}"/><text x="794" y="67" font-family="Arial" font-size="12" fill="{COLORS['ink']}">stability score</text>
<circle cx="910" cy="62" r="5" fill="{COLORS['coral']}"/><text x="924" y="67" font-family="Arial" font-size="12" fill="{COLORS['ink']}">chemical pressure</text>
</svg>"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg, encoding="utf-8")
    return path


def write_trajectory_figure(trajectory: pd.DataFrame, output_path: str | Path) -> Path:
    """Write an SVG showing normalized species trajectories."""

    path = Path(output_path)
    if len(trajectory) > 80:
        sample_index = np.linspace(0, len(trajectory) - 1, 80, dtype=int)
        trajectory = trajectory.iloc[sample_index].reset_index(drop=True)
    species = [column for column in trajectory.columns if column != "time"]
    palette = [COLORS["forest"], COLORS["coral"], COLORS["blue"], COLORS["violet"], COLORS["gold"], "#7a8c54"]
    normalized = trajectory[species].div(trajectory[species].max(axis=0).replace(0, 1), axis=1)
    x_positions = np.linspace(80, 1030, len(trajectory))
    lines = []
    legends = []
    for index, species_name in enumerate(species):
        y_positions = 430 - normalized[species_name].to_numpy() * 300
        lines.append(_polyline(list(zip(x_positions, y_positions)), palette[index % len(palette)]))
        legends.append(
            f'<rect x="{80 + (index % 3) * 250}" y="{490 + (index // 3) * 24}" width="12" height="4" fill="{palette[index % len(palette)]}"/>'
            f'<text x="{100 + (index % 3) * 250}" y="{496 + (index // 3) * 24}" font-family="Arial" font-size="11" fill="{COLORS["ink"]}">{escape(species_name)}</text>'
        )
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 560">
<rect width="1100" height="560" fill="{COLORS['paper']}"/>
<text x="60" y="58" font-family="Arial" font-size="26" font-weight="700" fill="{COLORS['ink']}">Integrated biocontrol trajectories</text>
<text x="60" y="84" font-family="Arial" font-size="13" fill="{COLORS['muted']}">Normalized abundance across the simulation horizon</text>
<line x1="80" y1="430" x2="1030" y2="430" stroke="{COLORS['grid']}"/>
<line x1="80" y1="130" x2="80" y2="430" stroke="{COLORS['grid']}"/>
{''.join(lines)}
{''.join(legends)}
</svg>"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg, encoding="utf-8")
    return path
